version: "3.8"

services:

  airflow:
    image: apache/airflow:2.9.3
    container_name: airflow_container
    restart: always

    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data

    ports:
      - "8080:8080"

    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Adil --lastname Khan --role Admin --email admin@example.com &&
      airflow webserver & airflow scheduler
      "

  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_USER: aimlock
      POSTGRES_PASSWORD: 9125
      POSTGRES_DB: weather_db

    ports:
      - "5432:5432"